apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: port-service-redis
  name: port-service-redis
spec:
  selector:
    app: redis-deployment
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
status:
  loadBalancer: {}
